config/routes.rb
Rails.application.routes.draw do
  get 'events/show'

  root 'events#index'

  resources :events

end

app/models/day.rb
class Day < ActiveRecord::Base
  belongs_to :event
  
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :days

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def show
    @event = Event.find(params[:id])
    respond_to do |format|
      format.html
      format.json {
        render :json => @event.days
      }
    end
  end

  def index
    @events = Event.all
  end

  def new
    render :new
  end

  def create
    seatgeek_id = event_params[:url].split('/')[-1]
    # @event = Event.new()
    url = "https://api.seatgeek.com/2/events/#{seatgeek_id}?client_id=NjEzOTI5MnwxNDc4MzkzNzA0"
    uri =  URI.parse(url)
    raw_body = Net::HTTP.get_response(uri).body
    response = JSON.parse(raw_body)

    if response['archived'] || response["status"] == "error"
      render :index
    end

    @event = Event.new(
      seatgeek_id: seatgeek_id,
      finished: false,
      title: response['title'],
      date: response['datetime_local'],
      venue_location: response['venue']['display_location'],
      venue_name: response['venue']['name']
    )

    if @event.save
      redirect_to event_url(@event)
    else
      render :index
    end
  end


  private

  def event_params
    params.require(:event).permit(:url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<div class="container-fluid">
  <h1>EventWatcher</h1>

  <div class="site_description">
    <span>
      EventWatcher checks ticket prices everyday. Click any of the events below to see how their prices have changed over time.
    </span>
  </div>

  <p>
  </p>

  <h4>Currently Tracked Events</h4>
  <ul class="ongoing_event_list">
    <% @events.select{|e| !e.finished }.each do |event| %>
      <li>
        <%= link_to event.title, event_path(event) %>
      </li>
    <% end %>
  </ul>

  <h4>Past Events</h4>
  <ul>
    <% @events.select{|e| e.finished }.each do |event| %>
      <li>
        <%= link_to event.title, event_path(event) %>
      </li>
    <% end %>
  </ul>
</div>

app/views/events/new.html.erb
<div class="container-fluid">
  <h1>Add a new Event to track</h1>

  <%= form_tag(controller: "events", action: "create") do %>

  <%= label_tag('event[url]', "Enter the seatgeek url of a concert you'd like to track") %>
  <%= text_field_tag('event[url]') %>
  <%= submit_tag("Create") %>

  <% end %>
</div>

app/views/events/show.html.erb
<div class="container-fluid">
  <h1><%= @event.title %></h1>
  <div class="">
    Show information:
  </div>
  <ul>
    <li>Date of performance: <%= @event.date %></li>
    <li>Location: <%= @event.venue_location %></li>
    <li>Venue name: <%= @event.venue_name %></li>
  </ul>


<div class="graph_options_wrapper">
  <div class="graph_options">
    <div class="graph_instructions">
      Click which price points you'd like to see:
    </div>
    <div class="">
      <div class="">
        <label for="low">
          <input type="checkbox" name="low" id="low" value="lowest_price" checked>
Lowest Price</label>
        <span class="low_color key_line"></span>
      </div>
      <div class="">
        <input type="checkbox" name="ave" id="ave" value="average_price" checked>
        <label for="ave">Average Price</label>
        <span class="ave_color key_line"></span>
      </div>
      <div class="">
        <input type="checkbox" name="high" id="high" value="highest_price">
        <label for="high">Highest Price</label>
        <span class="high_color key_line"></span>

      </div>
    </div>

  </div>
</div>

  <svg id="graph" width="1000" height="500"></svg>

  <%= javascript_include_tag 'graph' %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eventwatcher</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>